- name: install and configuring mysql
  hosts: localhost
  become: yes
  vars:
    #username: root
    password: ExpenseApp@1
    host: 54.196.140.32
  tasks:
  - name: install mysql
    dnf:
      name: mysql-server
      state: latest
  - name: start mysql
    service:
      name: mysqld
      state: started
      enabled: yes   
  - name: install mysql dependcies
    ansible.builtin.pip:
       name:
        - PyMySQL
        - cryptography
       executable: pip3.9  # pip3.11 if python version is 3.11

  - name: connection check & setup mysql cred
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ password }}"
      login_host: "{{ host }}"
      filter: version
    ignore_errors: yes
    register: mysqlsetupresult

  - name: display error result
    debug:
      msg: "errors while setup of mysql {{mysqlsetupresult}}"       



